publishers:

  robot_state:
    topic: /state_estimator/robot_state
    queue_size: 10
    latch: false
    min_frequency_rate: 0.1
    max_frequency_rate: 0.1

  pose_in_odom:
    topic: /state_estimator/pose_in_odom
    queue_size: 1
    latch: false

  pose_in_map:
    topic: /state_estimator/pose_in_map
    queue_size: 1
    latch: false

  twist:
    topic: /state_estimator/twist
    queue_size: 1
    latch: false
 